#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom &
setxkbmap -option caps:escape &
xset r rate 300 50 &
nitrogen --restore &
$HOME/.screenlayout/home-set.sh &
$HOME/.config/polybar/launch.sh &
clipmenud &
nm-applet &
trayer --edge bottom --align left --widthtype request --padding 3 --SetDockType true --SetPartialStrut true --expand true --monitor 1 --transparent true --alpha 180 --tint '#ffffff' &

bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor DP-1 -d 6 7 8 9 0

bspc config border_width         3
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color  "#4c566a"
bspc config focused_border_color "#FF9100"
bspc config presel_feeback_color "#FF9100"

bspc rule -a Zathura state=tiled
bspc rule -a discord desktop=5
