#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom &
setxkbmap -option caps:escape &
nitrogen --restore &
$HOME/.screenlayout/home-set.sh
$HOME/.config/polybar/launch.sh

bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor DP-1 -d 6 7 8 9 0

bspc config border_width         3
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color  "#4c566a"
bspc config focused_border_color "#FF9100"
bspc config presel_feeback_color "#FF9100"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^0'
bspc rule -a discord follow=off
