#!/bin/bash

BGREEN='\033[1;32m'

sudo rm /usr/local/bin/nvim
cd ~/Github/
sudo rm -rf neovim

echo -e "${BGREEN}========================================================================="
git clone https://github.com/neovim/neovim
echo -e "${BGREEN}========================================================================="
cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo
echo -e "${BGREEN}========================================================================="
sudo make install
echo -e "${BGREEN}========================================================================="
nvim --version
echo -e "${BGREEN}========================================================================="
cd $PWD
