#!/bin/bash

sudo rm /usr/local/bin/nvim
cd ~/Github/
sudo rm -rf neovim

echo "========================================================================="
git clone https://github.com/neovim/neovim
echo "========================================================================="
cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo
echo "========================================================================="
sudo make install
echo "========================================================================="
nvim --version
echo "========================================================================="
cd $PWD
