#!/bin/bash

BGREEN='\033[1;32m'

echo -e "${BGREEN}==============================Weather===================================="
curl wttr.in/Pattaya

echo -e "${BGREEN}============================Update YAY===================================="
yay --noconfirm -Syu
echo -e "${BGREEN}========================================================================="

echo -e "${BGREEN}=========================Get Crypto Update==============================="
cd ~/Github/crypto-watcher
bash update.sh
echo -e "${BGREEN}========================================================================="
notify-send -t 3000 "Crypto Watcher" "Done\!"
